<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Phone" nsURI="Phone" nsPrefix="Phone">
  <eClassifiers xsi:type="ecore:EClass" name="Phone">
    <eOperations name="call"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="credit" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tmp3_phoner" lowerBound="1"
        eType="#//PhoneR" eOpposite="#//PhoneR/tmp3_phone"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PhoneR">
    <eOperations name="placeCallR"/>
    <eOperations name="closeCallR"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="creditR" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="inCallR" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tmp3_phone" lowerBound="1"
        eType="#//Phone" eOpposite="#//Phone/tmp3_phoner"/>
  </eClassifiers>
</ecore:EPackage>
